CREATE TABLE `stock_daily_data_adjusted` (
  `STOCK_SYMBOL` varchar(10) NOT NULL,
  `TIME` datetime NOT NULL,
  `OPEN` double DEFAULT NULL,
  `CLOSE` double DEFAULT NULL,
  `HIGH` double DEFAULT NULL,
  `LOW` double DEFAULT NULL,
  `ADJUSTED_CLOSE` double DEFAULT NULL,
  `DIVIDEND_AMOUNT` double DEFAULT NULL,
  `VOLUME` double DEFAULT NULL,
  `SPLIT_COEFFICIENT` double DEFAULT NULL,
  `FINANCIAL_DATA_LOAD_ID` int(11) NOT NULL,
  PRIMARY KEY (`STOCK_SYMBOL`,`TIME`,`FINANCIAL_DATA_LOAD_ID`),
  KEY `FINANCIAL_DATA_LOAD_ID_idx` (`FINANCIAL_DATA_LOAD_ID`),
  CONSTRAINT `DAILY_FINANCIAL_DATA_LOAD_ID` FOREIGN KEY (`FINANCIAL_DATA_LOAD_ID`) REFERENCES `financial_data_load` (`data_load_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
